name: santhe
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  url_launcher: ^6.1.4
  smooth_page_indicator: ^1.0.0+2
  auto_size_text: ^3.0.0
  flutter_slidable: ^1.2.0
  flutter_svg: ^0.23.0+1
  http: ^0.13.4
  cached_network_image: ^3.2.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  pinput: 
  flutter_native_splash: ^2.0.5
  google_maps_flutter: ^2.1.2
  map_picker: ^0.0.3
  geolocator: ^8.2.0
  shared_preferences: ^2.0.13
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  firebase_database: ^9.0.15
  firebase_messaging: ^11.2.13
  grouped_list: ^4.2.0
  group_button: ^4.6.0
  image_picker: ^0.8.4+11
  timer_count_down: ^2.2.1
  flutter_html: ^2.2.1
  intl: ^0.17.0
  flutter_cache_manager: ^3.3.0
  dropdown_button2: ^1.2.2
  internet_connection_checker: ^0.0.1+3
  connectivity_plus: ^2.2.1
  easy_debounce: ^2.0.2+1
  flutter_local_notifications: ^9.4.0
  resize: ^1.0.0
  firebase_auth: ^3.3.13
  dartz: ^0.10.1
  equatable: ^2.0.3
  device_info_plus: ^3.2.3
  share_plus: ^4.0.4
  webview_flutter: ^2.0.4
  page_transition: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7

flutter_native_splash:
  color: '#FF9800'
  image: assets/splash.png
  banner: assets/banner.png
  android: true
  ios: true
  web: false

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/sent_tab/
    - assets/offers/
    - assets/fonts/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Black.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 900
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 400
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 200
        - asset: assets/fonts/Mulish-Regular.ttf