name: santhe
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+7

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  algolia: ^1.1.1
  android_play_install_referrer: ^0.2.1
  auto_size_text: ^3.0.0
  bloc: ^8.0.3
  responsive_builder: ^0.4.3
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.10
  connectivity_plus: ^2.2.1
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  get_it: ^7.2.0
  device_info_plus: ^4.0.0
  dropdown_button2: ^1.2.2
  easy_debounce: ^2.0.2+1
  equatable: ^2.0.3
  firebase_analytics: ^9.3.4
  firebase_auth: ^3.10.0
  firebase_core: ^1.23.0
  firebase_crashlytics: ^2.8.4
  firebase_database: ^9.1.5
  firebase_messaging: ^11.2.13
  firebase_storage: ^10.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_html: ^2.2.1
  flutter_image_compress: ^1.1.0
  flutter_local_notifications: ^9.4.0
  flutter_slidable: ^1.2.0
  flutter_svg: ^0.23.0+1
  geolocator: ^9.0.0
  get: ^4.6.5
  google_maps_flutter: ^2.1.2
  group_button: ^4.6.0
  grouped_list: ^4.2.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  http: ^0.13.4
  hydrated_bloc: ^8.1.0
  image_picker: ^0.8.4+11
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  location: ^4.4.0
  logger: ^1.1.0
  map_picker: ^0.0.3
  page_transition: ^2.0.5
  path_provider: ^2.0.11
  pinput: null
  resize: ^1.0.0
  share_plus: ^4.0.4
  shared_preferences: ^2.0.13
  smooth_page_indicator: ^1.0.0+2
  timer_count_down: ^2.2.1
  url_launcher: ^6.1.7
  webview_flutter: ^2.0.4
  youtube_player_flutter: ^8.1.1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.1.7
  change_app_package_name: ^1.1.0

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/sent_tab/
    - assets/offers/
    - assets/fonts/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Black.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 900
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 400
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 200
        - asset: assets/fonts/Mulish-Regular.ttf
